baseurl = "/"
languageCode = "en-us"
title = "Mathematics and Statistics"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/millerchangym"
	weight = 5

[params]
    footer = "&copy; 2019 [Yeng Miller-Chang](/about/) | [Github](https://github.com/millerchangym)"
