---
title: On Freshman-Level Statistics
author: Yeng Miller-Chang
date: "2019-05-04"
draft: true
tags:
  - statistics
  - education
---

To make sure that there is a shared understanding of what I mean by "freshman-level statistics," I am referring to a statistics course which is usually required for many liberal arts and health sciences majors, requires no calculus, and more or less, covers the same material as the [Advanced Placement (AP) Statistics syllabus](https://apcentral.collegeboard.org/pdf/ap-statistics-course-description.pdf?course=ap-statistics); i.e.,

- Measures of central tendency and spread

- Basic data visualizations

- Basic probability, some mention of the normal distribution

- Sampling distributions of the sample proportion and sample mean

- Hypothesis testing and confidence intervals (``$t$`` tests, ``$\chi^2$`` tests, etc.)

For many students, this will often be their only statistics course. I believe it is fair to say that the culmination of the entire course is hypothesis testing, as that is what the course content builds up to, until the very end.

I'm not going to cite any of the many examples that one can find online of the faults of hypothesis testing and the use of ``$p$``-values; however, I'd like to mention that the way this freshman-level statistics course is structured doesn't help matters at all.

## A ``$t$``-Test Example

Consider the following example, which I have run into in my professional work: suppose you manage cashiers in a retail store. You're not particularly interested in measuring any cashier's individual performance, but want to know how people feel about your cashiers overall. You've gotten complaints from various people about their experiences at your store.

To get an idea of how customers feel about your cashiers, you ask them a five-point question such as:

<center>
*How satisfied are you with how you were treated by your cashier today?*
</center>

with rating scale 1, 2, 3, 4, and 5; 5 being extremely satisfied, 3 being neutral, and 1 being extremely dissatisfied.

You survey 3000 people, and compute the average rating. The average score is 3.2, and let's suppose that the sample standard deviation is 0.3.

Because of the magnitude of complaints that you've gotten, you implement a training for your cashiers (because you have to), and you ask another 1000 people the same question as the previous one. The average score after the training is 3.3, with a standard deviation of 0.3.

```{r}
sattherwaite_df <- function(s_1, n_1, s_2, n_2) {
  numerator <- (s_1^2/n_1 + s_2^2/n_2)^2
  denominator <- (1/(n_1-1))*(s_1^2/n_1)^2 + (1/(n_2-1))*(s_2^2/n_2)^2
  return(numerator/denominator)
}

pt((3.3 - 3.2)/sqrt(0.3^2/1000 + 0.3^2/3000), 
   df = sattherwaite_df(0.3, 1000, 0.3, 3000), 
   lower.tail = FALSE) * 2
``` 
You decide that upon looking at this ``$p$``-value that, well, the ``$p$``-value is less than ``$0.01$``, so your training **must** have improved the customer experience with your cashiers!

